import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Header } from '../components/Header'
import { Footer } from '../components/Footer'
import { Treasure } from '../components/Treasure'
import AuthProvider from './AuthContext'

import { GetServerSideProps } from 'next'
import { InferGetServerSidePropsType } from 'next'
import { Treasures } from '../components/Treasures'

export const getServerSideProps: GetServerSideProps = async (context) => {
  // 作品一覧の読み込み場所
  // 🤗🤗デプロイ時変更🤗🤗
  const res = await fetch(`https://loving-kusu-4281.lolipop.io/metamon.php`)
  // const res = await fetch(`http://localhost/myfile_lab05/%20NFTMetaData/metamon.php`)
  
  const data = await res.json()
  console.log(data);
  
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

const Home: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <AuthProvider>
      <div className={styles.container}>
        <Head>
          <title>NEXTで作る卒制の旅</title>
          <meta name="description" content="Generated by create next app" />
          {/* bootstrapのレスポンシブ対応 */}
          <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main >
          <div >
            <Treasures data={data} />
            {/* <Treasure /> */}
          </div>
        </main>
        <Footer />
      </div>
    </AuthProvider>
  )
}

export default Home
